version: "3.9"
services:
  superhero:
    container_name: superhero
    image: knvelasquez/superhero:v2.0
    environment:
      # Sets default value 8080 if SPRING_BOOT_PORT is not defined
      - SPRING_BOOT_PORT=${SPRING_BOOT_PORT:-8080}
    ports:
      #Map default value 8080 if SPRING_BOOT_PORT is not defined
      - ${SPRING_BOOT_PORT:-8080}:${SPRING_BOOT_PORT:-8080}
    build:
      context: ./
      dockerfile: Dockerfile

  jwt-auth:
     container_name: jwt-auth
     image: knvelasquez/jwtauth:v1.3
     environment:
       # Sets default value 8082 if SPRING_BOOT_PORT is not defined
       - SPRING_BOOT_PORT=${SPRING_BOOT_PORT:-8082}
     ports:
       # Map default value 8082 if SPRING_BOOT_PORT is not defined
       - ${SPRING_BOOT_PORT:-8082}:${SPRING_BOOT_PORT:-8082}