version: "3.9"
services:
  superhero:
    container_name: superhero
    environment:
      # Sets default value 8080 if SPRING_BOOT_PORT is not defined
      - SPRING_BOOT_PORT=${SPRING_BOOT_PORT:-8080}
    ports:
      #Map default value 8080 if SPRING_BOOT_PORT is not defined
      - ${SPRING_BOOT_PORT:-8080}:${SPRING_BOOT_PORT:-8080}
    build:
      context: ./
      dockerfile: Dockerfile